[paths]
gwas = "/path/to/gwas/data"
trait = "/path/to/trait/data"
output = "/path/to/output"

[files]
gwas_output = "gwas_consortium_efforts.csv"
trait_output = "traits.csv"
sga_output = "shared_genetic_architecture.csv"

[processing]
gwas_delimiter = ","
trait_delimiter = "\t"